version: '3.9'
services:
  api:
    image: datascientest/fastapi:1.0.0
    container_name: api_container
    networks: 
      - network_test
    ports: 
      - "8000:8000"
  container_test1:
    image: image_test1
    container_name: container_test1
    build:
      context: .
      dockerfile: Dockerfile_test1
    networks: 
      - network_test
    environment:
      - API_ADDRESS=api
      - API_PORT=8000
      - LOG=1
    depends_on:
      - api
    volumes:
      - testvolume01:/test1
networks:
  network_test:
volumes:
  testvolume01: {}


